### ISSUE TITLE
[🐛 Bug ]: Chrome keeps crashing when latest version is installed

### ISSUE THREAD

**Issue by user19958** [budtmo/docker-android#358]
### Operating System

Ubuntu 22.04

### Docker Image

budtmo/docker-android:emulator_13.0

### Expected behaviour

I was trying to open chrome and navigate to google com by this simple code:
![obrazek](https://github.com/budtmo/docker-android/assets/134925911/c86821ff-b336-49fb-ae67-787cc07d8347)
but every time its show this exception:
`Exception has occurred: CLR/OpenQA.Selenium.WebDriverException
An unhandled exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll: 'An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to start com.android.chrome on device emulator-5554: Starting: Intent { dat=data: cmp=com.android.chrome/com.google.android.apps.chrome.Main }
Error type 3
Error: Activity class {com.android.chrome/com.google.android.apps.chrome.Main} does not exist.'`

On appium forum is information that this exception is related with chromedriver version. So i decide to update chrome by installing bundle via apkmirror installer.
But now every time chrome is opened app crash with this exception:
![obrazek](https://github.com/budtmo/docker-android/assets/134925911/d10df113-3d80-4414-83f2-9badbabcc30a)

Can anyone help me with proper way to install latest chrome in emulator ?

### Actual behaviour

Cannot open chrome it keeps crashing.

### Logs

**Chromedriver exception:**
`
Exception has occurred: CLR/OpenQA.Selenium.WebDriverException
An unhandled exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll: 'An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to start com.android.chrome on device emulator-5554: Starting: Intent { dat=data: cmp=com.android.chrome/com.google.android.apps.chrome.Main }
Error type 3
Error: Activity class {com.android.chrome/com.google.android.apps.chrome.Main} does not exist.'
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(Uri remoteAddress, ICapabilities appiumOptions)
   at Program.Main(String[] args) in /home/martin/appium/Program.cs:line 22`

**Chrome app crash log (adb logcat -b crash)**
`Process: com.android.chrome, PID: 9038
06-01 07:53:08.973  9038  9063 E AndroidRuntime: ml2: errorCode=2
06-01 07:53:08.973  9038  9063 E AndroidRuntime:        at org.chromium.base.library_loader.b.e(chromium-TrichromeChromeGoogle.aab-stable-573505836:142)
06-01 07:53:08.973  9038  9063 E AndroidRuntime:        at org.chromium.base.library_loader.b.a(chromium-TrichromeChromeGoogle.aab-stable-573505836:18)
06-01 07:53:08.973  9038  9063 E AndroidRuntime:        at pH.run(chromium-TrichromeChromeGoogle.aab-stable-573505836:5)
06-01 07:53:08.973  9038  9063 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
06-01 07:53:08.973  9038  9063 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: Failed at System.loadLibrary()
06-01 07:53:08.973  9038  9063 E AndroidRuntime:        at org.chromium.base.library_loader.d.b(chromium-TrichromeChromeGoogle.aab-stable-573505836:254)
06-01 07:53:08.973  9038  9063 E AndroidRuntime:        at org.chromium.base.library_loader.b.f(chromium-TrichromeChromeGoogle.aab-stable-573505836:48)
06-01 07:53:08.973  9038  9063 E AndroidRuntime:        at org.chromium.base.library_loader.b.e(chromium-TrichromeChromeGoogle.aab-stable-573505836:37)
06-01 07:53:08.973  9038  9063 E AndroidRuntime:        ... 3 more`

**Comment by hasanalpzengin** [comment]
I am having the same problem. Is there anyone managed to install recent chrome version and run it ?
