### ISSUE TITLE
[🐛 Bug ]: 

### ISSUE THREAD

**Issue by shubjain272001** [budtmo/docker-android#387]
### Operating System

Ubuntu 20.04

### Docker Image

budtmo/docker-android:emulator_11.0

### Expected behaviour

Emulator should get booted .

### Actual behaviour

![MicrosoftTeams-image (4)](https://github.com/budtmo/docker-android/assets/76242422/698d3740-bbce-407a-b46d-8be088392556)
![MicrosoftTeams-image (3)](https://github.com/budtmo/docker-android/assets/76242422/a77daf12-5b12-471d-9d98-a5d07c1af6bd)

### Logs

provided device_status.stdout.log above in pictures .

 I have run command -docker run -d --privileged -p 6080:6080 -p 4723:4723 -p 5555:5555 -p 9000:9000 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true  WEB_LOG= true - APPIUM=true --device /dev/kvm  --name android-container budtmo/docker-android:emulator_11.0

**Comment by shubjain272001** [comment]
@budtmo any suggestions ?

**Comment by biggiethehacker** [comment]
I am facing the same issue. Running on K8S with on KVM supported node. Here is my config - 
```
containers:
- name: appium-android-emulator
  image: myregistry.io/budtmo/docker-android:emulator_13.0_v2.15.0-p0
  imagePullPolicy: IfNotPresent
  securityContext:
    privileged: true
  env:
    - name: APPIUM 
      value: "true"
    - name: EMULATOR_DEVICE
      value: "Samsung Galaxy S10"
    - name: WEB_VNC
      value: "true"
    - name: CONNECT_TO_GRID
      value: "true"
    - name: APPIUM_HOST
      value: "127.0.0.1"
    - name: APPIUM_PORT
      value: "4723"
    - name: SELENIUM_HOST
      value: "selenium-hub"
    - name: SELENIUM_PORT
      value: "4444"     
  ports:
    - containerPort: 6080
      protocol: TCP
    - containerPort: 4723
      protocol: TCP
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
  volumeMounts:
    - mountPath: /dev/kvm
      name: kvm
volumes:
  - name: kvm
    hostPath:
      path: /dev/kvm
```

Device status - 

```
androidusr@appium-android-f9fc89ff8-mkqjz:~$ cat device_status 
BOOTING
```

Too many logs in device logs but here are the last few lines and a grep for error - 
```
2025-01-24 12:24:37 INFO Emulator - [attempt: 57] emulator is not booted! will check again in 2 seconds
2025-01-24 12:24:40 INFO Emulator - [attempt: 58] emulator is not booted! will check again in 2 seconds
2025-01-24 12:24:43 INFO Emulator - [attempt: 59] emulator is not booted! will check again in 2 seconds
Traceback (most recent call last):
  File "/usr/local/bin/docker-android", line 11, in <module>
    load_entry_point('docker-android', 'console_scripts', 'docker-android')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/androidusr/docker-android/cli/src/app.py", line 144, in start
    start_device()
  File "/home/androidusr/docker-android/cli/src/app.py", line 78, in start_device
    selected_device.wait_until_ready()
  File "/home/androidusr/docker-android/cli/src/device/emulator.py", line 200, in wait_until_ready
    self.check_adb_command(self.ReadinessCheck.BOOTED,
  File "/home/androidusr/docker-android/cli/src/device/emulator.py", line 193, in check_adb_command
    raise RuntimeError(
RuntimeError: booted is checked 59 times!
```

```
androidusr@appium-android-f9fc89ff8-mkqjz:~/logs$ cat device.stdout.log | grep -e Error -e ERROR -e error -e Exceptiion -e EXCEPTION -e
 exception
INFO         | SharedLibrary::open for [/opt/android/emulator/qemu/linux-x86_64/lib64/vulkan/libvulkan.so] failed (posix). dlerror: []
INFO         | SharedLibrary::open for [/opt/android/emulator/qemu/linux-x86_64/lib64/vulkan/libvulkan.so.1] failed (posix). dlerror: [
]
```

**Comment by biggiethehacker** [comment]
@shubjain272001 did you find a fix for this?
